---
- name: Install & Configure Nginx
  hosts: prod
  become: true

  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: latest
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: true
  - name: Copy
    copy:
      src: index.html
      dest: /var/www/html/
      
      
      
