---
- name: Install & Configure Nginx
  hosts: prod
  become: true

  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: latest
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: true
  - name: Sudoers Permission to Jenkins User
    community.general.sudoers:
      name: jenkins do as root
      state: present
      user: jenkons
      commands: ALL

  - name: Archive
    archive: 
      path: /var/lib/jenkins/workspace/production1/*
      dest: /tmp/classwebsite3.tar
  - name: Unarchive
    unarchive:
      src: /tmp/classwebsite3.tar
      dest: /var/www/html/
      extra_opts: ['--strip-components=5','--show-stored-names']

      
      
      
      
