---
- name: Install & Configure Nginx
  hosts: prod
  become: true

  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: latest
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: true
  - name: copy custom html
    copy:
      src: /var/lib/jenkins/workspace/production1/*
      dest: /var/www/html/
      
