---
- name: Install & Configure Apache2
  hosts: test
  become: true
  vars:
    - app: apache2

  tasks:
  - name: Install Apache2
    apt:
      name: "{{ app }}"
      state: latest
  - name: Start Apache2
    service:
      name: "{{ app }}" 
      state: started
      enabled: true
  - name: Sudoers Permission to Jenkins User
    community.general.sudoers:
      name: jenkins do as root
      state: present
      user: jenkins
      commands: ALL
  - name: Unarchive & Copy
    unarchive:
      src: /tmp/classwebsite3.tar
      dest: /var/www/html/
