name: General ci/cd

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  user: Souvik
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        env:
          date: 27may26
        
      - name: Create a dummy file
        run: |
          mkdir -p github-directory
          echo "Hello, this file is a created by $user on $date & save it to artifact!" > github-directory/github-file.txt

      - name: Upload the file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-generated-artifact
          path: github-directory/github-file.txt
          retaintion-days: 1
 
    
