name: ci/cd pipeline for secret_variable

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  name: Souvik

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: secret_variable
        run: |
          echo "GitHub Repository UserName: $name"
          echo "Github Account UserName: ${{ github.repository_owner }}"
          echo "Github Secret Value: ${{ secrets.my_secret }}"
